### ISSUE TITLE
python3.9 requests-cache error

### ISSUE THREAD

**Issue by 0xBoringWozniak** [neoctobers/etherscan#3]
AttributeError: module 'requests_cache' has no attribute 'core' for any requests

version: python3.9
requests version: 2.26.0
requests-cache: 0.8.1

**Comment by rzeydelis** [comment]
I have been getting the same error.

**Comment by 0xBoringWozniak** [comment]
https://github.com/neoctobers/etherscan/pull/2#issuecomment-953858481
